Add an upper bound for the Python version
On Python 3.12 and later the version of urllib3 required by gophish
fails to import with:
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'